# Site Info
title: '개발의숲'
tagline: '개발의숲'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: http://jonny-cho.github.io 
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

# About/contact
author:
  name: Jonny
  description:
  gravatar: # md5 hash of your email address
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/jonny-cho
    # facebook:  <hide>
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    email:     mailto:andante2183@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/blog/'
  Categories:           
    - '/'
    - { Categories All: '/blog/categories/' }
    - { 개발일기: '/blog/categories/#dev' }
    # - { 컴퓨터공학 : '/blog/categories/#cs' }
    - { Java: '/blog/categories/#java' }
    - { Spring: '/blog/categories/#spring' }
    - { JavaScript: '/blog/categories/#js' }
    - { SQL: '/blog/categories/#sql' }
    - { Python: '/blog/categories/#python' }
    - { Django: '/blog/categories/#django' }
    # - { Ruby on Rails: '/blog/categories/#ror' }
    # - { javascript: '/blog/categories/#javascript' }
    # - { nodejs: '/blog/categories/#nodejs' }
    # - { MySQL: '/blog/categories/#mySQL' }
    - { 알고리즘 문제풀이: '/blog/categories/#algorithm' }
    - { git: '/blog/categories/#git' }
    - { github pages: '/blog/categories/#githubpages' }
    # - { etc: '/blog/categories/#etc' }
    # - { Tags: '/blog/tags/' }

  About:          
    - '/about/'
  # Search:
  #   - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# hero:
#   image: /public/img/we_will_be_giants_by_yalestewart.jpg
#   caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-122658187-1' # leave blank if you don't want google analytics
disqus_short_name: 'jonny-cho-github-io' # leave blank if you don't want disqus

