name: Blog Deploy
run-name: Blog Deploy
on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com

          - name: GithubPages Deploy
            uses: enriikke/gatsby-gh-pages-action@v2.2.1
            with:
              access-token: ${{ secrets.GITHUB_TOKEN }}
              deploy-branch: gh-pages
              skip-publish: false

#          - name: Set Git User
#            run: |
#              git config user.email "andante2183@gmail.com"
#              git config user.name "Jonny-Cho"
#
#          - name: Run deploy
#            run: |
#              npm ci
#              npm run deploy
#          - name: Setup Node
#            uses: actions/setup-node@v3
#            with:
#              node-version-file: '.nvmrc'
#              cache: npm
#
#          - name: Set Git User
#            run: |
#              git config user.name "Jonny-Cho"
#              git config user.email "andante2183@gmail.com"
#
#          - name: Run deploy
#            run: |
#              npm ci
#              npm run deploy
