name: Blog Deploy
run-name: Blog Deploy
on:
  push:
    branches:
      - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Setup Node
            uses: actions/setup-node@v3
            with:
              node-version-file: '.nvmrc'
              cache: npm

          - name: Set Git User
            run: |
              git config user.name "Jonny-Cho"
              git config user.email "andante2183@gmail.com"

          - name: Run deploy
            run: |
              npm ci
              npm run deploy
