name: Blog Deploy
run-name: Blog Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              token: ${{ secrets.GITHUB_TOKEN }}

          - name: Setup Node
            uses: actions/setup-node@v3
            with:
              node-version-file: '.nvmrc'
              cache: npm

          - name: Set Git User
            run: |
              git config user.name "Jonny-Cho"
              git config user.email "andante2183@gmail.com"

          - name: Install dependencies
            run: npm ci

          - name: Build
            run: npx gatsby clean && npx gatsby build

          - name: Deploy to GitHub Pages
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./public
