name: Blog Deploy
run-name: Blog Deploy
on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Set Git User
            run: |
              git config user.name "Jonny-Cho"
              git config user.email "andante2183@gmail.com"
              git config init.defaultBranch "main"

          - name: GithubPages Deploy
            uses: enriikke/gatsby-gh-pages-action@v2
            with:
              access-token: ${{ secrets.GITHUB_TOKEN }}
              deploy-branch: gh-pages
