name: Blog Deploy
run-name: Blog Deploy
on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Setup Node
            uses: actions/setup-node@v3
            with:
              node-version-file: '.nvmrc'
              cache: npm
          - name: GithubPages Deploy
            uses: enriikke/gatsby-gh-pages-action@v2
            with:
              access-token: ${{ secrets.GITHUB_TOKEN }}
              deploy-branch: gh-pages
